Add Berlin Buzzwords and FOSS Backstage
rubyberlin/code-of-conduct pull request #170
Opened 2018-02-26 16:25 UTC by tthePB

2018-02-26 16:27 UTC, hagenburger requested changes

2018-02-26 16:27 UTC, hagenburger commented on data/supporters.json
> +          "phone":   "+493092105978"
There are several parsing errors in the JSON files. You can see the red markers here on Github. Please fix first. Thanks :)

2018-02-26 16:27 UTC, hagenburger commented on data/supporters.json
> +          "phone":   "+493092105977"
Also please use one space after the colon for the beauty of it :)

2018-02-26 16:27 UTC, hagenburger commented on data/supporters.json
> +    },
JSON does not allow a comma here (and other places).

2018-02-26 22:03 UTC, tthePB commented
Made all changes – hope everything works now. I'm something of a beginner, so thanks for the feedback, @hagenburger :)

2018-03-04 10:27 UTC, hagenburger requested changes
Hey @tthePB, we’re open for beginners and invite everybody to contribute and learn :) I added some more comments, please have a look.

Before you submit, you could check the syntax in the Terminal by parsing it either with Node:

```
node -e "const fs = require('fs'); console.log(JSON.parse(fs.readFileSync('data/supporters.json')))"
```

or with Ruby:

```
ruby -e "require 'json'; puts JSON.parse(File.read('data/supporters.json'))"
```

Both will either output the JSON (but compressed) or raise an error.

2018-03-04 10:27 UTC, hagenburger commented on data/supporters.json
> +         {
Please align the curly braces below each other for the beauty of it:

```
       },
       {
```

2018-03-04 10:27 UTC, hagenburger commented on data/supporters.json
> +        },
Only add a comma, when another opening `{` is following. The last item in JSON must not have a comma (in JavaScript this would be allowed though).

2018-03-04 10:27 UTC, hagenburger commented on data/supporters.json
> +        },
See comment above.

2018-03-04 10:27 UTC, hagenburger commented on data/supporters.json
> +         {
See comment above.

2018-03-04 10:27 UTC, hagenburger commented on data/supporters.json
> +        {
See comment above.

2018-05-24 05:58 UTC, hagenburger commented
Hey @tthePB, is there anything I can do for you with this pull request? Let me know if you have any questions!

2018-05-29 15:28 UTC, tthePB commented
Thanks @hagenburger, I just had no capacity in the last weeks. Will have a look at the comments you gave soon :)

2025-06-24 17:40 UTC, chastell commented
Hey, thanks so much and thanks for your patience!

Due to the JSON nature of the file I had to rebase it by hand and couldn’t update this PR, but I merged it to `main` (with your commit’s authorship preserved) and it’s now also live on the website. :heavy_check_mark:

2025-06-24 17:40 UTC, closed without merging